add_library(SDL2::core INTERFACE IMPORTED)

if(EMSCRIPTEN)
    set_property(TARGET SDL2::core PROPERTY INTERFACE_COMPILE_OPTIONS -s USE_SDL=2)
    set_property(TARGET SDL2::core PROPERTY INTERFACE_LINK_FLAGS -s USE_SDL=2)
else()
    set_property(TARGET SDL2::core PROPERTY INTERFACE_LINK_LIBRARIES SDL2)
endif()
